name: codifyr
description: A CLI tool for generating LLM-friendly codemaps for Flutter projects
version: 0.1.1
homepage: https://github.com/originoss/codifyr
repository: https://github.com/originoss/codifyr
issue_tracker: https://github.com/originoss/codifyr/issues

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  equatable: ^2.0.7
  mason_logger: ^0.3.3
  pub_updater: ^0.5.0
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.15
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^7.0.0

executables:
  codifyr:
